development:
  adapter: postgresql
  database: rb_db
  host: pgsqlflex-postgres.database.azure.com
  url: jdbc:postgresql://pgsqlflex-postgres.database.azure.com:5432/rb_db
  username: dbadmin
  password: **removing on purpose**
  pool: 5
  port: 5432


